name = "ExtendableFEMBase"
uuid = "12fb9182-3d4c-4424-8fd1-727a0899810c"
version = "1.4.0"
authors = ["Christian Merdon <merdon@wias-berlin.de>", "Patrick Jaap <patrick.jaap@wias-berlin.de>"]

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"

[weakdeps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[extensions]
ExtendableFEMBaseUnicodePlotsExt = ["UnicodePlots"]

[compat]
DiffResults = "1"
DifferentiationInterface = "0.7.10"
DocStringExtensions = "0.8,0.9"
ExtendableGrids = "1.13.0"
ExtendableSparse = "1.5.1"
ForwardDiff = "0.10.35, 1"
LinearAlgebra = "1.9"
Polynomials = "2.0.21, 3, 4"
Printf = "1.9"
SparseArrays = "1.9"
SparseConnectivityTracer = "1.1.2"
SparseMatrixColorings = "0.4.22"
SpecialPolynomials = "0.4.9, 0.5"
UnicodePlots = "3.6"
julia = "1.9"
